//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disaster_Management_System.User_Pages.Meteorologi_Dept.Meteorologi_Dept_Head
{


    public partial class Edit_Profile_Meteorologi_Head
    {
    }
}
