//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disaster_Management_System.User_Pages.Meteorologi_Dept.Meterologi_Team_Member
{


    public partial class Team_Meteorologi_TeamMember
    {
    }
}
