//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disaster_Management_System.User_Pages.Disater_Management_Dept.Resque_Team.Resque_Team_Member
{


    public partial class AlertsHub_Resque_TeamMember
    {
    }
}
